version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
environment:
  NPM_TOKEN:
    secure: FRgWoOWDue045JOJaaOe5UtkhGLVXp5qkv0uTdhChC8HBxaxRk5hgnqn5hvmMx+M
build_script:
- ps: >-
    .\build_npm.ps1